name: vetjirani_flutter
description: A Flutter app connecting vets and farmers in Kenya for improved livestock health.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.5.0
  firebase_messaging: ^14.6.4
  geoflutterfire2: ^2.3.3
  provider: ^6.0.5
  google_fonts: ^4.0.4
  flutter_local_notifications: ^13.0.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
